#!/bin/bash
#
# $Id$
#
### BEGIN INIT INFO
# Provides: samba
# Short-Description: This is a daemon which starts and stops the Samba 4 service
# Description: This is a daemon which starts and stops the Samba 4 service, it has been adpated from the rdisc script used in CentOS 6.5
### END INIT INFO

# chkconfig: - 41 89
# config: /etc/sysconfig/samba

# Source function library.
. /etc/init.d/functions
. /etc/sysconfig/network

#
# Set default options.  Override the defaults and define 
# custom options in /etc/sysconfig/samba
#

LOCKFILE=/var/lock/subsys/samba

[ -f /etc/sysconfig/samba ] && . /etc/sysconfig/samba


start() {
	# Check that networking is configured.
	[ ${NETWORKING} = "no" ] && exit 1

	echo -n $"Starting Samba4: "
	if [ $UID -ne 0 ]; then
                RETVAL=4
                failure
        else
		daemon /usr/local/samba/sbin/samba 
		RETVAL=$?
		[ $RETVAL -eq 0 ] && touch $LOCKFILE
	fi;
	echo
	return $RETVAL
}

stop() {
	echo -n $"Shutting down Samba4 services: "
	if [ $UID -ne 0 ]; then
                RETVAL=4
                failure
        else
        	killproc /usr/local/samba/sbin/samba
		RETVAL=$?
	        [ $RETVAL -eq 0 ] && rm -f $LOCKFILE
        fi;
	echo
	return $RETVAL
}

restart() {
	stop
	start
}

RETVAL=0

# See how we were called.
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  status)
	status samba
	;;
  restart|reload)
	restart
	;;
  condrestart)
	if status $prog > /dev/null; then
	    stop
	    start
	fi
	;;
  *)
	echo $"Usage: $0 {start|stop|status|restart|reload}"
	exit 2
esac

exit $?
